#!/usr/bin/expect -f
set timeout 120
spawn ssh -o StrictHostKeyChecking=no root@173.199.93.201 "ufw allow 22/tcp && ufw allow 80/tcp && ufw allow 443/tcp && ufw allow 8080/tcp && ufw allow 8081/tcp && ufw allow 8082/tcp && ufw allow 3000/tcp && ufw allow 9090/tcp && ufw --force enable && cd /root/revns/revns && docker-compose -f docker-compose.prod.yml up -d"
expect "*?assword:*" {
    send {4{yW+.[7*F[#BP}(}
    send "\r"
}
expect eof
